import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { AppHeader, BottomNav } from '../components/AppShell'
import { Icon } from '../components/Icon'
import { TransactionRow, type Transaction } from '../components/TransactionRow'

const transactions: Transaction[] = [{ icon:'coffee',merchant:'Blue Bottle Coffee',meta:'Food & Drink • Today',amount:'-$12.45',kind:'Debit'},{icon:'home',merchant:'Metropolis Rentals',meta:'Housing • Oct 1',amount:'-$2,100.00',kind:'Auto-pay'},{icon:'card',merchant:'Apple Inc.',meta:'Salary • Sep 30',amount:'+$6,400.00',kind:'Income',income:true},{icon:'bag',merchant:'Uniqlo Global',meta:'Shopping • Sep 29',amount:'-$89.90',kind:'Debit'}]
function Comparison({label,amount,width,active=false}:{label:string;amount:string;width:string;active?:boolean}) { return <div><div className="mb-2 flex justify-between"><span className="text-sm text-[#5c5d64]">{label}</span><span className={`font-mono text-sm ${active?'text-[#00714d]':''}`}>{amount}</span></div><div className="h-2 rounded-full bg-[#f2f4f6]"><div className={`h-full rounded-full ${active?'bg-[#00865d]':'bg-[#c6c6cd]'}`} style={{width}} /></div></div> }

export function DashboardPage() { const [open,setOpen]=useState(false); const navigate=useNavigate(); return <div className="min-h-screen bg-[#f7f9fb]"><AppHeader /><main className="mx-auto max-w-7xl px-5 pb-28 pt-24 sm:px-8"><section className="mb-8 grid gap-6 lg:grid-cols-3"><article className="summary-card relative overflow-hidden lg:col-span-2"><p className="eyebrow">Monthly spending</p><div className="mt-3 flex items-center gap-3"><strong className="text-[40px] font-bold sm:text-5xl">$4,820.50</strong><span className="trend-pill"><Icon name="trendDown" className="size-4" />12.5%</span></div><div className="mt-10 flex h-32 items-end gap-2">{[40,60,46,75,90,50,66].map((h,i)=><span key={i} className={`flex-1 rounded-t-lg ${i===4?'bg-black':'bg-[#e0e3e5]'}`} style={{height:`${h}%`}} />)}</div></article><article className="summary-card border-l-4 border-l-[#00865d]"><p className="eyebrow">Monthly comparison</p><div className="mt-5 space-y-4"><Comparison label="Last Month" amount="$5,508.20" width="100%"/><Comparison label="Current" amount="$4,820.50" width="87%" active/></div><p className="mt-7 text-sm leading-6 text-[#5c5d64]">You've spent <strong className="text-black">$687.70 less</strong> than last month. You're on track for your savings goal!</p></article></section><section><div className="mb-3 flex justify-between"><h2 className="text-xl font-semibold">Recent Transactions</h2><button className="text-xs font-semibold uppercase text-[#00714d]">View all</button></div><div className="overflow-hidden rounded-2xl border bg-white">{transactions.map(t=><TransactionRow key={t.merchant} transaction={t}/>)}</div></section></main><div className={`fab-menu ${open?'fab-menu--open':''}`}><button onClick={()=>navigate('/receipts/scan')}><span>Scan Receipt</span><Icon name="scan" className="size-5"/></button><button onClick={()=>navigate('/expenses/new')}><span>Manual Entry</span><Icon name="plus" className="size-5"/></button></div><button aria-label="Open quick actions" onClick={()=>setOpen(!open)} className="fab"><Icon name={open?'plus':'scan'} className="size-7"/></button><BottomNav active="home"/></div> }
