import { type FormEvent, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Icon } from '../components/Icon'

function GoogleMark() { return <svg aria-hidden="true" className="size-5" viewBox="0 0 24 24"><path fill="#4285F4" d="M21.6 12.2c0-.7-.1-1.5-.2-2.2H12v4.3h5.4a4.6 4.6 0 0 1-2 3v2.8h3.5c2-1.9 3.2-4.6 3.2-7.9Z" /><path fill="#34A853" d="M12 22c2.9 0 5.3-1 7-2.6l-3.5-2.8a6.3 6.3 0 0 1-9.4-3.3H2.5v2.8A10 10 0 0 0 12 22Z" /><path fill="#FBBC05" d="M6.1 13.3a6 6 0 0 1 0-3.8V6.7H2.5a10 10 0 0 0 0 9.4l3.6-2.8Z" /><path fill="#EA4335" d="M12 5.4c1.6 0 3.1.6 4.3 1.7L19.4 4A10.4 10.4 0 0 0 2.5 6.7l3.6 2.8A6 6 0 0 1 12 5.4Z" /></svg> }

export function LoginPage() {
  const [showPassword, setShowPassword] = useState(false), [submitting, setSubmitting] = useState(false)
  const navigate = useNavigate()
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitting(true); window.setTimeout(() => navigate('/dashboard'), 700) }
  return <div className="auth-page"><div className="auth-glow auth-glow--mint" /><div className="auth-glow auth-glow--blue" /><main className="relative z-10 w-full max-w-[440px] animate-enter"><header className="mb-10 text-center"><div className="mx-auto mb-6 grid size-16 place-items-center rounded-2xl bg-black text-white shadow-xl"><Icon name="sparkles" className="size-8 fill-current" /></div><h1 className="text-[32px] font-semibold tracking-tight sm:text-[36px]">Aura Finance</h1><p className="mt-2 text-[#45464d]">Step into financial serenity</p></header><section className="rounded-3xl border border-[#c6c6cd]/50 bg-white p-6 shadow-lg sm:p-8"><form className="space-y-6" onSubmit={submit}><div className="space-y-2"><label className="field-label" htmlFor="email">Email address</label><div className="field-shell"><Icon name="mail" className="field-icon" /><input id="email" type="email" autoComplete="email" placeholder="name@company.com" required className="field-input" /></div></div><div className="space-y-2"><div className="flex justify-between"><label className="field-label" htmlFor="password">Password</label><button type="button" className="text-xs font-semibold">Forgot?</button></div><div className="field-shell"><Icon name="lock" className="field-icon" /><input id="password" type={showPassword ? 'text' : 'password'} autoComplete="current-password" placeholder="••••••••" required className="field-input pr-12" /><button type="button" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? 'Hide password' : 'Show password'} className="absolute inset-y-0 right-0 grid w-12 place-items-center text-[#76777d]"><Icon name={showPassword ? 'eyeOff' : 'eye'} className="size-5" /></button></div></div><div className="space-y-4 pt-2"><button disabled={submitting} className="primary-button">{submitting ? <><span className="spinner" /> Signing in…</> : 'Sign in with email'}</button><div className="flex items-center gap-4 text-xs uppercase text-[#76777d]"><span className="h-px flex-1 bg-[#c6c6cd]" />or<span className="h-px flex-1 bg-[#c6c6cd]" /></div><button type="button" className="secondary-button"><GoogleMark />Continue with Google</button></div></form></section><footer className="mt-8 text-center text-sm text-[#45464d]">New to Aura?<button className="ml-2 font-bold text-black">Create Account</button></footer></main></div>
}
